BIT-239 mongo repo
LykkeCity/Lykke.Service.BlockchainWallets pull request #61
Opened 2019-03-12 15:57 UTC by some-dev

2019-03-13 21:34 UTC, KonstantinRyazantsev commented on src/Lykke.Service.BlockchainWallets.AzureRepositories/Backup/BlockchainWalletsBackupRepository.cs
> +            await _isPrimaryIndexStorage.DeleteIfExistAsync(BlockchainWalletsBackupIsPrimaryIndex.GetPartitionKey(clientId),
don't we need to do this only if IsPrimaryWallet returned true?

2019-03-13 21:34 UTC, KonstantinRyazantsev commented on src/Lykke.Service.BlockchainWallets.MongoRepositories/Wallets/BlockchainWalletMongoRepository.cs
> +        public async Task InsertBatchAsync(IEnumerable<(string blockchainType, Guid clientId, string address, CreatorType createdBy, bool addAsLatest)> wallets)
latest vs primary -> different terms in the same domain is not good

2019-03-13 21:34 UTC, KonstantinRyazantsev commented on src/Lykke.Service.BlockchainWallets.MongoRepositories/Wallets/BlockchainWalletMongoRepository.cs
> +                Id = ObjectId.GenerateNewId(DateTime.UtcNow),
Id is a timestamp, or it is based in the timestamp + some random?

2019-03-13 21:34 UTC, KonstantinRyazantsev commented on src/Lykke.Service.BlockchainWallets.MongoRepositories/Wallets/BlockchainWalletMongoRepository.cs
> +        public async Task AddAsync(string blockchainType, Guid clientId, string address, CreatorType createdBy,
Race condition is possible in this method, is Mongo support optimistic concurrency?

2019-03-13 21:34 UTC, KonstantinRyazantsev commented on src/Lykke.Service.BlockchainWallets.MongoRepositories/Wallets/BlockchainWalletMongoRepository.cs
> +                var nextWallet = (await _collection.WrapQueryAsync(_log,
Looks like nextWallet will be the same as entityToDelete, since entityToDelete is primary here, the is likely the first entity in OrderByDescending(p => p.Inserted) collection.

2019-03-13 21:34 UTC, KonstantinRyazantsev commented on src/Lykke.Service.BlockchainWallets.MongoRepositories/Wallets/BlockchainWalletMongoRepository.cs
> +            }
Looks like actual deletion/archiving/removing IsPrimary flag of entityToDelete is missed

2019-03-13 21:34 UTC, KonstantinRyazantsev commented on src/Lykke.Service.BlockchainWallets.MongoRepositories/Wallets/BlockchainWalletMongoRepository.cs
> +        public Task<(IEnumerable<WalletDto> Wallets, string ContinuationToken)> GetAllAsync(Guid clientId,
It's not GetAll actually, this method returns only primary wallets

2019-03-13 21:34 UTC, KonstantinRyazantsev commented on src/Lykke.Service.BlockchainWallets.MongoRepositories/Wallets/BlockchainWalletMongoRepository.cs
> +                skip = ContinuationTokenModel.Deserialize(continuationToken).Skip;
why continuation token is not just ```int``` which is actually "how many items already read"?

2019-03-13 21:34 UTC, KonstantinRyazantsev commented on src/Lykke.Service.BlockchainWallets.MongoRepositories/Wallets/BlockchainWalletMongoRepository.cs
> +                    Skip = skip + take
```skip + entities.Count``` will be more accurate value

2019-03-13 21:34 UTC, KonstantinRyazantsev commented on src/Lykke.Service.BlockchainWallets.MongoRepositories/Wallets/BlockchainWalletMongoRepository.cs
> +        public async Task<WalletDto> TryGetAsync(string blockchainType, Guid clientId)
TryGetPrimaryAsync?

2019-03-13 21:34 UTC, KonstantinRyazantsev commented on src/Lykke.Service.BlockchainWallets.MongoRepositories/Wallets/BlockchainWalletMongoRepository.cs
> +                    query => query.Where(p => p.ClientId == clientId && p.BlockchainType == blockchainType)
Can't see index for this query. Is Mongo use most suitable index which contain required fields in this case or full scan is executed?

2019-03-13 21:34 UTC, KonstantinRyazantsev commented on src/Lykke.Service.BlockchainWallets.MongoRepositories/Wallets/BlockchainWalletMongoRepository.cs
> +                query.Where(p => p.ClientId == clientId && p.BlockchainType == blockchainType), take, continuationToken);
Can't see index for this query

2019-03-13 21:34 UTC, KonstantinRyazantsev commented on src/Lykke.Service.BlockchainWallets.MongoRepositories/Wallets/BlockchainWalletMongoRepository.cs
> +                query.Where(p => p.ClientId == clientId && p.IsPrimary), take, continuationToken);
Can't see index for this query

2019-03-13 21:34 UTC, KonstantinRyazantsev commented on src/Lykke.Service.BlockchainWallets.MongoRepositories/Wallets/BlockchainWalletMongoRepository.cs
> +        private async Task CreateSupportClientIdPrimaryWalletsQueryAsync()
Isn't this index also covered by CreateSinglePrimaryWalletPerClientConsistencyIndex ?

2019-03-13 21:34 UTC, KonstantinRyazantsev commented on src/Lykke.Service.BlockchainWallets.MongoRepositories/Wallets/CreatedTypeMappingExtensions.cs
> +            return (Contract.CreatorType)source;
better to map via switch/case to throw exception, if unknown value is passed (here and below)

2019-03-13 21:34 UTC, KonstantinRyazantsev commented on src/Lykke.Service.BlockchainWallets.MongoRepositories/Wallets/WalletMongoEntity.cs
> +        [BsonElement("clid")]
can we use normal names without shortening?

2019-03-13 21:34 UTC, KonstantinRyazantsev commented on tools/Lykke.Service.BlockchainWallets.MongoIndexesBuilder/Program.cs
> +                LogFactory.Create().AddConsole());
Replace with AddUnbufferedConsole() or dispose log factory in the end.

2019-03-13 21:34 UTC, KonstantinRyazantsev commented on tools/Lykke.Service.BlockchainWallets.ObsoleteAzureToMongoMigrator/Program.cs
> +            var logfactory = LogFactory.Create().AddConsole();
AddUnbufferedConsole() or dispose logFactory in the end

2019-03-13 21:34 UTC, KonstantinRyazantsev commented on tools/Lykke.Service.BlockchainWallets.ObsoleteAzureToMongoMigrator/Program.cs
> +                Console.WriteLine($"[{DateTime.UtcNow}] Ensuring indexes created");
Better to use logger otherwise output can be merged (everywhere in the tools)

2019-03-13 21:34 UTC, KonstantinRyazantsev commented on tools/Lykke.Service.BlockchainWallets.RestoreBackupToPrimaryStorage/Program.cs
> +            var logFactory = LogFactory.Create().AddConsole();
As above

2019-03-13 21:34 UTC, KonstantinRyazantsev commented on tools/Lykke.Service.BlockchainWallets.RestoreBackupToPrimaryStorage/Program.cs
> +                    await walletMongoRepo.AddAsync(walletData.integrationLayerId, walletData.clientId, walletData.address,
Can be batch insert as in the migration tool

2019-03-13 22:21 UTC, some-dev commented on src/Lykke.Service.BlockchainWallets.MongoRepositories/Wallets/BlockchainWalletMongoRepository.cs
> +                Id = ObjectId.GenerateNewId(DateTime.UtcNow),
https://docs.mongodb.com/manual/reference/method/ObjectId/
it-is sort of sequential guid with smaller size.

2019-03-13 22:25 UTC, some-dev commented on src/Lykke.Service.BlockchainWallets.MongoRepositories/Wallets/WalletMongoEntity.cs
> +        [BsonElement("clid")]
As far as i know it's good practice to keep mongo entity as small as it possible (with prop names) - as it cached in RAM

2019-03-13 23:00 UTC, some-dev commented on src/Lykke.Service.BlockchainWallets.MongoRepositories/Wallets/BlockchainWalletMongoRepository.cs
> +                query.Where(p => p.ClientId == clientId && p.BlockchainType == blockchainType), take, continuationToken);
CreateSupportClientIdPrimaryWalletsQueryAsync used here i believe 
http://learnmongodbthehardway.com/schema/indexes/

2019-03-13 23:00 UTC, some-dev commented on src/Lykke.Service.BlockchainWallets.MongoRepositories/Wallets/BlockchainWalletMongoRepository.cs
> +                query.Where(p => p.ClientId == clientId && p.IsPrimary), take, continuationToken);
CreateSupportClientIdPrimaryWalletsQueryAsync used here i believe 
http://learnmongodbthehardway.com/schema/indexes/

2019-03-13 23:01 UTC, some-dev commented on src/Lykke.Service.BlockchainWallets.MongoRepositories/Wallets/BlockchainWalletMongoRepository.cs
> +        private async Task CreateSupportClientIdPrimaryWalletsQueryAsync()
it is unique filtered index to ensure the consistency - not to speed up the queries

2019-03-13 23:10 UTC, some-dev commented on src/Lykke.Service.BlockchainWallets.AzureRepositories/Backup/BlockchainWalletsBackupRepository.cs
> +            await _isPrimaryIndexStorage.DeleteIfExistAsync(BlockchainWalletsBackupIsPrimaryIndex.GetPartitionKey(clientId),
Looks like this not needed at all.

2019-03-13 23:14 UTC, some-dev commented on src/Lykke.Service.BlockchainWallets.MongoRepositories/Wallets/BlockchainWalletMongoRepository.cs
> +                    query => query.Where(p => p.ClientId == clientId && p.BlockchainType == blockchainType)
CreateSupportClientIdPrimaryWalletsQueryAsync Is used i believe

Builders<WalletMongoEntity>.IndexKeys.Combine(clientIdAsc, isPrimaryDesc, blockchainTypeAsc)
http://learnmongodbthehardway.com/schema/indexes/

2019-03-14 06:08 UTC, cassade requested changes

2019-03-14 06:08 UTC, cassade commented on src/Lykke.Service.BlockchainWallets.AzureRepositories/Backup/BlockchainWalletsBackupRepository.cs
> +            return (mapped.Where(p=>!p.IsDeleted).Select(p=> (p.integrationLayerId, p.clientId, p.address, p.createdBy, p.isPrimary)),
Materialize result to prevent multiple enumeration and execution of async `IsPrimaryWallet` and `IsDeleted` requests (even if you know that `SelectAsync` does it - it's not obvious).

2019-03-14 06:08 UTC, cassade commented on src/Lykke.Service.BlockchainWallets.MongoRepositories/Wallets/BlockchainWalletMongoRepository.cs
> +        public async Task AddAsync(string blockchainType, Guid clientId, string address, CreatorType createdBy,
Is it possible to use natural deterministic keys instead of ObjectId? It would allow to use _upsert_ almost always and avoid race conditions.

2019-03-15 10:37 UTC, KonstantinRyazantsev commented on src/Lykke.Service.BlockchainWallets.AzureRepositories/Backup/BlockchainWalletsBackupRepository.cs
> +            return (mapped.Where(p=>!p.IsDeleted).Select(p=> (p.integrationLayerId, p.clientId, p.address, p.createdBy, p.isPrimary)),
Agree. And use IReadOnlyCollection instead of IEnumerable as return type of this method and upper on the call stack to prevent excess materialization.

2019-03-15 10:37 UTC, KonstantinRyazantsev commented on src/Lykke.Service.BlockchainWallets.MongoRepositories/Wallets/BlockchainWalletMongoRepository.cs
> +            var enumerated = wallets as (string blockchainType, Guid clientId, string address, CreatorType createdBy, bool isPrimary)[] ?? wallets.ToArray();
Cast to IReadOnlyCollection instead of array will be more correct here

2019-03-15 10:37 UTC, KonstantinRyazantsev commented on src/Lykke.Service.BlockchainWallets.MongoRepositories/Wallets/BlockchainWalletMongoRepository.cs
> +                        throw new OptimisticConcurrencyException();
Pass ```e``` as inner exception

2019-03-15 10:37 UTC, KonstantinRyazantsev commented on src/Lykke.Service.BlockchainWallets.MongoRepositories/Wallets/BlockchainWalletMongoRepository.cs
> +                if (primary?.Address == address)
Race condition with InsertOrUpdatePrimaryWalletAsync is possible. This method can decide that there is no primary wallet, but InsertOrUpdatePrimaryWalletAsync in another thread can set the address as the primary wallet, then this method will remove wallet from the allWalletsCollection and we will have item in the primary wallets collection without corresponding item in the all wallets collection. Of couse this case is rare, just noted.

2019-03-15 10:37 UTC, KonstantinRyazantsev commented on src/Lykke.Service.BlockchainWallets.Services/WalletService.cs
> +            } while (!completed && retryCounter <= maxRetries);
Consider to use Polly instead of custom logic

2019-03-15 15:31 UTC, cassade submitted a review, later dismissed

2019-03-15 15:38 UTC, cassade submitted a review, later dismissed

2019-03-15 22:23 UTC, KonstantinRyazantsev approved these changes

2019-03-17 22:15 UTC, merged